mediathekview/plugin.video.mediathekview

- addon.xml
- classes/exceptions.py
- classes/storesqlite.py
- classes/updater.py
- Dramatic speedup of update with SQLite
- Handling of database corruption
> Branch for speedup and 0.2.8

- addon.py
- addon.xml
- classes/filmui.py
- classes/updater.py
- resources/language/English/strings.po
- resources/language/German/strings.po
- resources/language/Italian/strings.po
Download is now also compatible with Kodi VFS paths
> Download is now also compatible with Kodi VFS paths

- addon.py
- addon.xml
- classes/channelui.py
- classes/filmui.py
- classes/initialui.py
- classes/mvupdate.py
- classes/notifier.py
- classes/settings.py
- classes/showui.py
- classes/store.py
- classes/storemysql.py
- classes/storesqlite.py
- classes/ttml2srt.py
- classes/updater.py
- de/yeasoft/base/Logger.py
- de/yeasoft/kodi/KodiAddon.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.it_it/strings.po
- service.py
- Better error debug
- Removed error prone stuff
- Improved Code Style
- Removed unused code
> Make Codacy (and Kodi Admins) Happy

- addon.py
- addon.xml
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/lib/base/Logger.py
- resources/lib/channelui.py
- resources/lib/filmui.py
- resources/lib/initialui.py
- resources/lib/kodi/KodiAddon.py
- resources/lib/kodi/KodiUI.py
- resources/lib/mvupdate.py
- resources/lib/mvutils.py
- resources/lib/notifier.py
- resources/lib/settings.py
- resources/lib/showui.py
- resources/lib/storemysql.py
- resources/lib/storesqlite.py
- resources/lib/ttml2srt.py
- resources/lib/updater.py
- resources/settings.xml
- In "Alle Sendungen nach Sender" kommt man nun direkt nach der Auswahl des Senders in die Filmliste
- Die Anzahl Tage die ein Film als "Vor kurzem hinzugefügt" gilt, ist nun einstellbar
- Es ist einstellbar, ob "Vor kurzem hinzugefügt" das Sendedatum oder das Datum des Hinzufügens in der Datenbank berücksichtigt
- Anzahl der neuen Filme in "Vor Kurzem hinzugefügt nach Sender" stimmt nun
- Übersetzungsfehler korrigiert
> Code Qualität und Usability

- addon.py
- addon.xml
- resources/lib/filmui.py
- resources/lib/showui.py
- resources/lib/storemysql.py
- resources/lib/storesqlite.py
- Freitext-Suche benutzt nun prepared statements
- Fehler in MySQL Abfrage behoben (Closes #39)
> Verbesserungen und Fehlerbehebungen im SQL Code

- README.md
- addon.py
- addon.xml
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/lib/kodi/KodiUI.py
- resources/lib/mvupdate.py
- resources/lib/notifier.py
- resources/lib/settings.py
- resources/lib/store.py
- resources/lib/storemysql.py
- resources/lib/storesqlite.py
- resources/lib/updater.py
- resources/settings.xml
- service.py
- Verschiedene Aktualisierungsmodi (Manuell, Beim Start, Automatisch) sparen Bandbreite und Energie
- Datenbank kann nun auch im Betrieb umkonfiguriert bzw. gewechselt werden
- Abspielen eines Films aus den Suchergebnissen löscht nun die Liste nicht mehr
> Bandwidth and energy saving features

- README.md
- addon.py
- addon.xml
- resources/lib/settings.py
- resources/lib/storemysql.py
- resources/lib/updater.py
- resources/settings.xml
- service.py
- "Update bei Start" aktualisiert erst beim ersten Addon-Aufruf
- Typ und Version der SQL Datenbank wird nun im Log angezeigt
> UpdateMode 2 war wohl nicht so wie beabsichtigt

- README.md
- addon.py
- addon.xml
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/lib/mvupdate.py
- resources/lib/settings.py
- resources/lib/updater.py
- resources/settings.xml
- "mvupdate" hat die neuen Optionen --force und --intervall
- Verschiedene Optionen bezüglich NFO-Dateien
- Automatische Erkennung von Staffel und Folge
- Verbesserte Download-Einstellungen
> Verbesserungen im Download

- addon.py
- addon.xml
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/lib/filmui.py
- resources/lib/kodi/KodiUI.py
- resources/lib/mvupdate.py
- resources/lib/notifier.py
- resources/lib/settings.py
- resources/lib/store.py
- resources/lib/storemysql.py
- resources/lib/storesqlite.py
- resources/lib/updater.py
- resources/settings.xml
- service.py
Das hier könnte die Probleme mit manchen MySQL/MariaDB bzgl. zu großer Indizes lösen.
p.s.: Der Pull-Request ist aus versehen gigantisch geworden. Er enthält nun:
* #70 - Effizientere Datenbankstruktur
* #67 - Letzte Suchvorgänge
* #81 - Möglichkeit eine Sendung als Film oder als Episode einer Serie herunterzuladen
> Gesammelter Pull Request mit #67, #70 und #81

- .gitignore
- addon.py
- addon.xml
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/lib/downloader.py
- resources/lib/kodi/KodiAddon.py
- resources/lib/mvutils.py
- resources/lib/searches.py
- resources/lib/storemysql.py
- resources/lib/storesqlite.py
* Better implementation of Recent Searches (Closes #67)
* Refactoring of download function
* First preparation for project wide linting and PEP8 conformity
> Better implementation of Recent Searches (Closes #67)

- addon.py
- addon.xml
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/lib/downloader.py
- resources/lib/filmui.py
- resources/lib/kodi/KodiAddon.py
- resources/lib/mvupdate.py
- resources/lib/searches.py
- resources/lib/settings.py
- resources/settings.xml
Play with subtitles (Closes #78)
> Play with subtitles (Closes #78)

- addon.py
- resources/language/resource.language.it_it/strings.po
- resources/lib/downloader.py
- resources/lib/filmui.py
See https://github.com/xbmc/repo-plugins/pull/1979
> Improvements after Kodi-PR-Review

- README.md
- addon.xml
- resources/lib/mvupdate.py
- resources/lib/updater.py
* Possibility to force a full update from command line #108 - Replacement for PR #107
> Implemented full update option (Closes #108)

- .gitignore
- addon.xml
- resources/lib/kodi/kodiaddon.py
- resources/lib/mvutils.py
- resources/lib/updater.py
- Workaround for broken gzip library on Kodi for Android (Closes #103)
- Python 3 compatibility (Closes #116)
- Fix for crash in `mvupdate` with mysql since V0.6.0 (Closes #118)
> Combined Pull Reuest for #103, #116 and #118

- resources/lib/mvupdate.py
- resources/lib/mvutils.py
- resources/lib/storesqlite.py
- resources/lib/updater.py
used the patch file and tested. Work for windows, ubuntu, libreelec so far without errors
> apply patch from ahpohl for #135

- resources/lib/downloader.py
- resources/lib/filmui.py
- resources/lib/kodi/kodiaddon.py
- resources/lib/kodi/kodilogger.py
- resources/lib/plugin.py
- resources/lib/settings.py
Fixing the windows umlaut in home path issue
> Unicode issue96

- resources/lib/channelui.py
- resources/lib/filmui.py
- resources/lib/initialui.py
- resources/lib/kodi/kodiaddon.py
- resources/lib/showui.py
angeblich verbessert diese Einstellung die performance bei rendern von langen Listen. Es ist Kodi 19 kompat und schaded anscheinend auch nicht. lets go for it
> added offscreen param to support quick renderer

- resources/lib/storemysql.py
Fixes #160 
Man könnte darüber nachdenken, ob es vorteilhafter wäre, die C-Extension immer zu benutzen, wenn sie verfügbar ist und dafür den `except`-Block entsprechend anzupassen.
> Never use mysql-connector's C extension

- resources/lib/mvupdate.py
> More robust version extraction for standalone mvupdate

- resources/lib/storemysql.py
Die Funktion ft_insert_film des Mysql-Treibers wurde so umgeschrieben, dass diese nun alle Datensätze eines Commits (1.000 Stück) im Bulk-Modus in eine temporäre Tabelle überträgt und diese durch Mengenoperationen in die film-Tabelle überträgt. Dadurch reduziert sich die Laufzeit eines kompletten DB-Aufbaus / eines kompletten DB-Updates von gefühlt Unendlich auf ca. 6 Minuten auf meinem i5-Laptop und schätzungsweise 10 Minuten auf einem Odroid C2. Beides gegen einen MariaDB-Docker auf meinem i5-basierten Homeserver.
Die notwendigen Änderungen beschränken sich (inhaltlich) allein auf die Funktion ft_insert_film. Die Prozedur ftInsertFilm diente als Vorlage für die notwendigen DB-Operationen, ist nun aber obsolet. Der neue Ablauf ist wie folgt.
1.  ft_insert_film wird vom Updater mit den …
> Implementierung von Bulk-Insert in storemysql.py zur Verbesserung der Update-Performance
